baseURL: "www.dennysinaga.com"
languageCode: en-us
title: Blog - Denny Abraham Sinaga
theme: PaperMod

enableEmoji: true

params:
  author: Denny Abraham Sinaga

menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
  
