baseURL: "www.dennysinaga.com"
title: nagabonor@denny
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true

params:
  title: Denny Abraham Sinaga
  description: "i write random stuffs here, please read it"
  keywords: [Portfolio]
  author: Denny Abraham Sinaga
  ShowCodeCopyButtons: true

# profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Denny Abraham Sinaga
    subtitle: "seeking opportunities and building expertise in the field of cybersecurity."
    imageUrl: "https://avatars.githubusercontent.com/u/62960949"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Denny Abraham Sinaga
    buttons:
      - name: about
        url: "/about"
      - name: blog
        url: "/blog"
  
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/dennyabrahamsinaga"
    - name: github
      url: "https://github.com/dennyabrahamsinaga"

menu:
  main:
    - identifier: profile
      name: about
      url: /about/
      weight: 10
    - identifier: blog
      name: blog
      url: /blog/
      weight: 20

